### PR TITLE
Updates and corrections

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by kmark** [comment]
Normally I'd stress for more testing on the Xposed min version change but since it's not going to hurt anyone on 54 and above there may be no need. Thanks.

**Comment by ghost** [comment]
The guy that originally reported the issue confirmed that the change worked. I then checked to see if any of the popular Xposed modules use 42+ and found that GravityBox did. So I think that it's safe to say that if GravityBox doesn't run into any issues then XHangouts shouldn't either.

**Comment by kmark** [comment]
Another potential issue is we're still linking against v54 but I'm not even
sure if the v44 jar is still available anywhere. We could accidentally use
a new 54 API that's not present on 44 (assuming there are any). Since it's
working as-is for the user at XDA I'd say there's no need to spend any
extra time on it. Even my old Droid X2 on a custom JB 4.1 ROM is v54
capable. I imagine the number of Xposed users below that API level is
miniscule.

**Comment by ghost** [comment]
The guy with this issue has a Cherry Mobile Flare S3 Mini. He's said that it's rooted and that only Xposed Installer 2.5.1 works on that device, so it's not a widespread issue.

GravityBox links against v54 too, so I don't think we're using any API that didn't previously exist. Like you originally said though, it shouldn't hurt anyone who keeps up to date anyway.

**Pull request merged**
