### PR TITLE
Hangouts 6.0.107278502 support, fixes and improvements

### PR DESCRIPTION
**Pull request by ghost**
The drawables were created by me. They're based off of the ic_account_circle SVG released by Google.

https://github.com/google/material-design-icons

APN splicing doesn't work, so that needs to either be fixed or removed. You'll also want to increase the XHangouts version number yourself.

You might also want to look into coloring the green picture and sticker icons.

### CODE REVIEW

**Comment by kmark** [comment]
Thanks for the PR. Your hard work on this is much appreciated. What we'll probably do for APN Splicing is orphan it (removing its inclusion in `XHangouts.java`) and leave it in the repo for the time being. The related settings will be hidden.

I'll start testing this now. Other than `MmsApnSplicing`, just `UiQuickSettings` has not been updated? Doesn't look like `UiDisableProximity` or `Sound` will need any changes since they're pretty version agnostic.

I haven't looked into this yet but is there any significant reason why `ImageResizing`, `ImageCompression`, and `MmsResizing` are separate mods? Judging by their similar goals it might be a good idea to merge them. Not sure yet though.

**Comment by ghost** [comment]
They're mainly separate files for readability. That plus they have different goals e.g. MmsResizing is used for just MMS via your carrier where as ImageResizing and ImageCompression are used throughout the whole of Hangouts. That's why I changed the wording and the display order of some of the options.

UiQuickSettings still appears to work and the others files that you mentioned work perfectly too. Honestly, if it wasn't for APN splicing being broken then this would be 100% functional right now. I would still like to address the green picture and sticker icons though. I think they might be getting colored via code.

**Comment by kmark** [comment]
Great, thanks. I'm on Freenode right now as `KevinM` if you want to converse more quickly. Just send me a PM there if you'd like. It might be easier to merge this PR in and then base your additional sticker changes off the merge. I'm about half way done the review.

**Comment by kmark** [comment]
Merged everything in as-is. A few tweaks here and there that I might make to clean things up but functionally it's looking great. Thank you. Feel free to open another PR whenever you'd like.

**Pull request merged**
