### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by ghost**
- Google Voice MMS lost quality after commit d8ec922 because you'd accidently set the target width and height to what Hangouts assigns instead of our custom dimensions.
- The dialers avatar icons weren't getting colored because the dialer uses default_avatar_large instead of default_avatar  :confused:
- The dialer uses a PNG file that we can't color match via hue adjustments, so I've replaced it with Googles logo.
- I suspect that issue #15 is something to do with Marshmallow as I can't replicate it on Lollipop or older.

### CODE REVIEW

**Comment by kmark** [comment]
Removing the configuration reload in #15 seemed to fix the problem without noticeably breaking anything. The process was always flaky especially on Android 4.x (but now on 6.x too?). I'm having a hard time determining why v2.3 was broken on Marshmallow but previous releases were (apparently) not. It could honestly be some kind of race condition that has to do with the order of initialized Xposed modules. I guess trying to retrieve/use a Context in handleInitPackageResources is bad practice™ since we can't be sure what state the Context is in.

**Comment by blackbox87** [comment]
It could be a bug in Xposed or it could be due to changes in Marshmallow. If removing the code doesn't cause any issues though then I wouldn't worry about it too much.

You can merge this if you want to now. Everything should be 100% stable.

There was one guy on XDA who reported a force close, but he didn't provide any debug info at all. My guess is that he didn't reboot after updating the module or he was using an old version of Hangouts.

**Comment by ghost** [comment]
It could be a bug in Xposed or it could be due to changes within Marshmallow. If removing the code doesn't cause any issues though then I wouldn't worry about it too much.

You can merge this PR if you want to now as everything should be stable.

[There was one guy on XDA who reported a force close](http://forum.xda-developers.com/showpost.php?p=64703814&postcount=612), but he didn't provide any debug info at all. My guess is that he didn't reboot after updating the module or he was using an old version of Hangouts.

**Comment by kmark** [comment]
Agreed. This should be sufficient enough to release a patch.

**Pull request merged**
